#!/bin/bash
git rm vimfiles/.editorconfig
git rm vimfiles/README.markdown
git rm vimfiles/README.md
git rm vimfiles/README.mkd
git rm vimfiles/after/ftplugin/mkd.vim
git rm vimfiles/after/ftplugin/python_pydiction.vim
git rm vimfiles/after/plugin/help.vim
git rm vimfiles/after/syntax/help.vim
git rm vimfiles/after/syntax/scala.vim
git rm vimfiles/autoload/Align.vim
git rm vimfiles/autoload/AlignMaps.vim
git rm vimfiles/autoload/bm.vim
git rm vimfiles/autoload/bm_sign.vim
git rm vimfiles/autoload/classpath.vim
git rm vimfiles/autoload/clojurecomplete.vim
git rm vimfiles/autoload/gist.vim
git rm vimfiles/autoload/pythoncomplete.vim
git rm vimfiles/autoload/tcomment.vim
git rm vimfiles/autoload/togglebg.vim
git rm vimfiles/autoload/util.vim
git rm vimfiles/autoload/xolox/misc.vim
git rm vimfiles/autoload/xolox/misc/buffer.vim
git rm vimfiles/autoload/xolox/misc/complete.vim
git rm vimfiles/autoload/xolox/misc/escape.vim
git rm vimfiles/autoload/xolox/misc/format.vim
git rm vimfiles/autoload/xolox/misc/list.vim
git rm vimfiles/autoload/xolox/misc/msg.vim
git rm vimfiles/autoload/xolox/misc/open.vim
git rm vimfiles/autoload/xolox/misc/option.vim
git rm vimfiles/autoload/xolox/misc/os.vim
git rm vimfiles/autoload/xolox/misc/path.vim
git rm vimfiles/autoload/xolox/misc/str.vim
git rm vimfiles/autoload/xolox/misc/test.vim
git rm vimfiles/autoload/xolox/misc/tests.vim
git rm vimfiles/autoload/xolox/misc/timer.vim
git rm vimfiles/autoload/xolox/misc/version.vim
git rm vimfiles/bitmaps/togglebg.png
git rm vimfiles/clj/.gitignore
git rm vimfiles/clj/dev-resources/test-inherit-indent.in
git rm vimfiles/clj/dev-resources/test-inherit-indent.out
git rm vimfiles/clj/project.clj
git rm vimfiles/clj/src/vim_clojure_static/generate.clj
git rm vimfiles/clj/src/vim_clojure_static/test.clj
git rm vimfiles/clj/test/vim_clojure_static/indent_test.clj
git rm vimfiles/clj/test/vim_clojure_static/syntax_test.clj
git rm vimfiles/clj/vim/test-runtime.vim
git rm vimfiles/colors/Mustang.vim
git rm vimfiles/colors/adaryn.vim
git rm vimfiles/colors/adrian.vim
git rm vimfiles/colors/aiseered.vim
git rm vimfiles/colors/anokha.vim
git rm vimfiles/colors/anotherdark.vim
git rm vimfiles/colors/aqua.vim
git rm vimfiles/colors/astroboy.vim
git rm vimfiles/colors/astronaut.vim
git rm vimfiles/colors/asu1dark.vim
git rm vimfiles/colors/autumn.vim
git rm vimfiles/colors/autumn2.vim
git rm vimfiles/colors/autumnleaf.vim
git rm vimfiles/colors/baycomb.vim
git rm vimfiles/colors/bclear.vim
git rm vimfiles/colors/bigbang.vim
git rm vimfiles/colors/biogoo.vim
git rm vimfiles/colors/blackbeauty.vim
git rm vimfiles/colors/blacksea.vim
git rm vimfiles/colors/bluegreen.vim
git rm vimfiles/colors/borland.vim
git rm vimfiles/colors/breeze.vim
git rm vimfiles/colors/brookstream.vim
git rm vimfiles/colors/buttercream.vim
git rm vimfiles/colors/calmar256-dark.vim
git rm vimfiles/colors/calmar256-light.vim
git rm vimfiles/colors/calmbreeze.vim
git rm vimfiles/colors/camo.vim
git rm vimfiles/colors/candy.vim
git rm vimfiles/colors/candycode.vim
git rm vimfiles/colors/chela_light.vim
git rm vimfiles/colors/chocolateliquor.vim
git rm vimfiles/colors/clarity.vim
git rm vimfiles/colors/cleanphp.vim
git rm vimfiles/colors/colorer.vim
git rm vimfiles/colors/dante.vim
git rm vimfiles/colors/darkZ.vim
git rm vimfiles/colors/darkblue2.vim
git rm vimfiles/colors/darkbone.vim
git rm vimfiles/colors/darkburn.vim
git rm vimfiles/colors/darkgit.vim
git rm vimfiles/colors/darkslategray.vim
git rm vimfiles/colors/darkspectrum.vim
git rm vimfiles/colors/dawn.vim
git rm vimfiles/colors/deepblue.vim
git rm vimfiles/colors/dejavu.vim
git rm vimfiles/colors/denim.vim
git rm vimfiles/colors/desert.vim
git rm vimfiles/colors/desert256.vim
git rm vimfiles/colors/desertEx.vim
git rm vimfiles/colors/desertink.vim
git rm vimfiles/colors/deveiate.vim
git rm vimfiles/colors/dusk.vim
git rm vimfiles/colors/dw_blue.vim
git rm vimfiles/colors/dw_cyan.vim
git rm vimfiles/colors/dw_green.vim
git rm vimfiles/colors/dw_orange.vim
git rm vimfiles/colors/dw_purple.vim
git rm vimfiles/colors/dw_red.vim
git rm vimfiles/colors/dw_yellow.vim
git rm vimfiles/colors/earendel.vim
git rm vimfiles/colors/eclipse.vim
git rm vimfiles/colors/ekvoli.vim
git rm vimfiles/colors/fine_blue.vim
git rm vimfiles/colors/fine_blue2.vim
git rm vimfiles/colors/fnaqevan.vim
git rm vimfiles/colors/fog.vim
git rm vimfiles/colors/freya.vim
git rm vimfiles/colors/fruit.vim
git rm vimfiles/colors/fruity.vim
git rm vimfiles/colors/fu.vim
git rm vimfiles/colors/gaea.vim
git rm vimfiles/colors/gentooish.vim
git rm vimfiles/colors/github.vim
git rm vimfiles/colors/golden.vim
git rm vimfiles/colors/greyhouse.vim
git rm vimfiles/colors/guardian.vim
git rm vimfiles/colors/gummybears.vim
git rm vimfiles/colors/habilight.vim
git rm vimfiles/colors/hemisu.vim
git rm vimfiles/colors/herald.vim
git rm vimfiles/colors/impact.vim
git rm vimfiles/colors/imperial.vim
git rm vimfiles/colors/inkpot.vim
git rm vimfiles/colors/intellij.vim
git rm vimfiles/colors/ironman.vim
git rm vimfiles/colors/jammy.vim
git rm vimfiles/colors/jellybeans.vim
git rm vimfiles/colors/kellys.vim
git rm vimfiles/colors/leo.vim
git rm vimfiles/colors/lettuce.vim
git rm vimfiles/colors/liquidcarbon.vim
git rm vimfiles/colors/lucius.vim
git rm vimfiles/colors/luinnar.vim
git rm vimfiles/colors/manuscript.vim
git rm vimfiles/colors/manxome.vim
git rm vimfiles/colors/marklar.vim
git rm vimfiles/colors/maroloccio.vim
git rm vimfiles/colors/martin_krischik.vim
git rm vimfiles/colors/masmed.vim
git rm vimfiles/colors/matrix.vim
git rm vimfiles/colors/mayansmoke.vim
git rm vimfiles/colors/metacosm.vim
git rm vimfiles/colors/mickeysoft.vim
git rm vimfiles/colors/midnight.vim
git rm vimfiles/colors/midnight2.vim
git rm vimfiles/colors/mizore.vim
git rm vimfiles/colors/molokai.vim
git rm vimfiles/colors/monokai.vim
git rm vimfiles/colors/montz.vim
git rm vimfiles/colors/moria.vim
git rm vimfiles/colors/moss.vim
git rm vimfiles/colors/motus.vim
git rm vimfiles/colors/navajo-night.vim
git rm vimfiles/colors/navajo.vim
git rm vimfiles/colors/neon.vim
git rm vimfiles/colors/neverness.vim
git rm vimfiles/colors/newspaper.vim
git rm vimfiles/colors/night.vim
git rm vimfiles/colors/night_vision.vim
git rm vimfiles/colors/nightshimmer.vim
git rm vimfiles/colors/no_quarter.vim
git rm vimfiles/colors/northland.vim
git rm vimfiles/colors/nuvola.vim
git rm vimfiles/colors/oceanblack.vim
git rm vimfiles/colors/oceandeep.vim
git rm vimfiles/colors/oceanlight.vim
git rm vimfiles/colors/olive.vim
git rm vimfiles/colors/omen.vim
git rm vimfiles/colors/papayawhip.vim
git rm vimfiles/colors/paradox.vim
git rm vimfiles/colors/peaksea.vim
git rm vimfiles/colors/print_bw.vim
git rm vimfiles/colors/psclone.vim
git rm vimfiles/colors/pyte.vim
git rm vimfiles/colors/railscasts.vim
git rm vimfiles/colors/railscasts2.vim
git rm vimfiles/colors/rdark.vim
git rm vimfiles/colors/relaxedgreen.vim
git rm vimfiles/colors/robinhood.vim
git rm vimfiles/colors/rootwater.vim
git rm vimfiles/colors/satori.vim
git rm vimfiles/colors/scame.vim
git rm vimfiles/colors/sea.vim
git rm vimfiles/colors/settlemyer.vim
git rm vimfiles/colors/sienna.vim
git rm vimfiles/colors/silent.vim
git rm vimfiles/colors/simpleandfriendly.vim
git rm vimfiles/colors/softblue.vim
git rm vimfiles/colors/solarized.vim
git rm vimfiles/colors/sorcerer.vim
git rm vimfiles/colors/soso.vim
git rm vimfiles/colors/spring.vim
git rm vimfiles/colors/summerfruit256.vim
git rm vimfiles/colors/synic.vim
git rm vimfiles/colors/tango.vim
git rm vimfiles/colors/tango2.vim
git rm vimfiles/colors/taqua.vim
git rm vimfiles/colors/tcsoft.vim
git rm vimfiles/colors/tesla.vim
git rm vimfiles/colors/tir_black.vim
git rm vimfiles/colors/tolerable.vim
git rm vimfiles/colors/torte.vim
git rm vimfiles/colors/twilight.vim
git rm vimfiles/colors/two2tango.vim
git rm vimfiles/colors/vc.vim
git rm vimfiles/colors/vibrantink.vim
git rm vimfiles/colors/vimhut.vim
git rm vimfiles/colors/vividchalk.vim
git rm vimfiles/colors/vylight.vim
git rm vimfiles/colors/winter.vim
git rm vimfiles/colors/wombat.vim
git rm vimfiles/colors/wombat256.vim
git rm vimfiles/colors/wombat256mod.vim
git rm vimfiles/colors/wood.vim
git rm vimfiles/colors/wuye.vim
git rm vimfiles/colors/xemacs.vim
git rm vimfiles/colors/xoria256.vim
git rm vimfiles/colors/zenburn.vim
git rm vimfiles/colors/zendnb.vim
git rm vimfiles/colors/zenesque.vim
git rm vimfiles/colors/zmrok.vim
git rm vimfiles/compiler/lein.vim
git rm vimfiles/complete-dict
git rm vimfiles/doc/Align.txt
git rm vimfiles/doc/TurboMark.txt
git rm vimfiles/doc/bufexplorer.txt
git rm vimfiles/doc/classpath.txt
git rm vimfiles/doc/clojure.txt
git rm vimfiles/doc/commentary.txt
git rm vimfiles/doc/detectindent.txt
git rm vimfiles/doc/easygrep.txt
git rm vimfiles/doc/ft-gitcommit-plugin.txt
git rm vimfiles/doc/fugitive.txt
git rm vimfiles/doc/gist-vim.txt
git rm vimfiles/doc/matchit.txt
git rm vimfiles/doc/misc.txt
git rm vimfiles/doc/numbered.txt
git rm vimfiles/doc/scala.txt
git rm vimfiles/doc/solarized.txt
git rm vimfiles/doc/surround.txt
git rm vimfiles/doc/tags
git rm vimfiles/doc/tags-ja
git rm vimfiles/doc/tcomment.txt
git rm vimfiles/doc/votl_cheatsheet.txt
git rm vimfiles/doc/votl_readme.txt
git rm vimfiles/filetype.vim
git rm vimfiles/ftdetect/clojure.vim
git rm vimfiles/ftdetect/git.vim
git rm vimfiles/ftdetect/javascript.vim
git rm vimfiles/ftdetect/mkd.vim
git rm vimfiles/ftdetect/scala.vim
git rm vimfiles/ftdetect/votl.vim
git rm vimfiles/ftplugin/clojure.vim
git rm vimfiles/ftplugin/git.vim
git rm vimfiles/ftplugin/gitcommit.vim
git rm vimfiles/ftplugin/gitconfig.vim
git rm vimfiles/ftplugin/gitrebase.vim
git rm vimfiles/ftplugin/gitsendemail.vim
git rm vimfiles/ftplugin/mkd.vim
git rm vimfiles/ftplugin/ocaml_enhcomm.vim
git rm vimfiles/ftplugin/php_enhcomm.vim
git rm vimfiles/ftplugin/python_fn.vim
git rm vimfiles/ftplugin/scala.vim
git rm vimfiles/ftplugin/scala.xpt.vim
git rm vimfiles/ftplugin/votl.vim
git rm vimfiles/indent/README
git rm vimfiles/indent/clojure.vim
git rm vimfiles/indent/gitconfig.vim
git rm vimfiles/indent/javascript.vim
git rm vimfiles/indent/mkd.vim
git rm vimfiles/indent/scala.vim
git rm vimfiles/indent/sh.vim
git rm vimfiles/indent/testfile.scala
git rm vimfiles/misc/easytags/highlight.py
git rm vimfiles/misc/easytags/why-so-slow.py
git rm vimfiles/plugin/.editorconfig
git rm vimfiles/plugin/AlignMapsPlugin.vim
git rm vimfiles/plugin/AlignPlugin.vim
git rm vimfiles/plugin/ScrollColor.vim
git rm vimfiles/plugin/StripWhiteSpaces.vim
git rm vimfiles/plugin/TurboMark.vim
git rm vimfiles/plugin/auto-pairs.vim
git rm vimfiles/plugin/beautifier.vim
git rm vimfiles/plugin/beautify-min.js
git rm vimfiles/plugin/beautify.js
git rm vimfiles/plugin/beautify.min.js
git rm vimfiles/plugin/bufexplorer.vim
git rm vimfiles/plugin/bufgrep.vim
git rm vimfiles/plugin/cecutil.vim
git rm vimfiles/plugin/classpath.vim
git rm vimfiles/plugin/commentary.vim
git rm vimfiles/plugin/cream-capitalization.vim
git rm vimfiles/plugin/easygrep.vim
git rm vimfiles/plugin/easygrepfileassociations
git rm vimfiles/plugin/fugitive.vim
git rm vimfiles/plugin/gist.vim
git rm vimfiles/plugin/hexman.vim
git rm vimfiles/plugin/matchit.vim
git rm vimfiles/plugin/mru.vim
git rm vimfiles/plugin/numbered.vim
git rm vimfiles/plugin/scala.vim
git rm vimfiles/plugin/surround.vim
git rm vimfiles/plugin/tasklist.vim
git rm vimfiles/plugin/tcomment.vim
git rm vimfiles/plugin/tests/test.js
git rm vimfiles/plugin/zoom.vim
git rm vimfiles/pydiction.py
git rm vimfiles/registry/mkd.yaml
git rm vimfiles/spec/fixtures/multiple_newlines.expected.scala
git rm vimfiles/spec/fixtures/multiple_newlines.scala
git rm vimfiles/spec/fixtures/no_newline.expected.scala
git rm vimfiles/spec/fixtures/no_newline.scala
git rm vimfiles/spec/fixtures/no_newline_after.expected.scala
git rm vimfiles/spec/fixtures/no_newline_after.scala
git rm vimfiles/spec/fixtures/no_package.expected.scala
git rm vimfiles/spec/fixtures/no_package.scala
git rm vimfiles/spec/fixtures/vanilla.expected.scala
git rm vimfiles/spec/fixtures/vanilla.scala
git rm vimfiles/spec/import_sorting_spec.rb
git rm vimfiles/spec/spec_helper.rb
git rm vimfiles/syntax/clojure.vim
git rm vimfiles/syntax/git.vim
git rm vimfiles/syntax/gitcommit.vim
git rm vimfiles/syntax/gitconfig.vim
git rm vimfiles/syntax/gitrebase.vim
git rm vimfiles/syntax/gitsendemail.vim
git rm vimfiles/syntax/javascript.vim
git rm vimfiles/syntax/mkd.vim
git rm vimfiles/syntax/python.vim
git rm vimfiles/syntax/scala.vim
git rm vimfiles/syntax/testfile.scala
git rm vimfiles/syntax/votl.vim
git rm vimfiles/test/multiple_headers.md
git rm vimfiles/test/syntax.md
git rm vimfiles/vimoutliner/plugin/prev/votl_hoist.otl
git rm vimfiles/vimoutliner/plugin/prev/votl_hoist.vim
git rm vimfiles/vimoutliner/plugin/votl_checkbox.otl
git rm vimfiles/vimoutliner/plugin/votl_checkbox.vim
git rm vimfiles/vimoutliner/plugin/votl_clock.vim
git rm vimfiles/vimoutliner/plugin/votl_format.vim
git rm vimfiles/vimoutliner/plugin/votl_gtd.vim
git rm vimfiles/vimoutliner/plugin/votl_math.otl
git rm vimfiles/vimoutliner/plugin/votl_math.vim
git rm vimfiles/vimoutliner/plugin/votl_newhoist.vim
git rm vimfiles/vimoutliner/plugin/votl_smart_paste.vim
git rm vimfiles/vimoutliner/plugin/votl_tags.vim
git rm vimfiles/vimoutliner/scripts/MediaWiki2otl
git rm vimfiles/vimoutliner/scripts/MediaWiki2otl.desc
git rm vimfiles/vimoutliner/scripts/Node/COPYING
git rm vimfiles/vimoutliner/scripts/Node/COPYING.GPL
git rm vimfiles/vimoutliner/scripts/Node/COPYING.LPDTL.1.0
git rm vimfiles/vimoutliner/scripts/Node/INSTALL
git rm vimfiles/vimoutliner/scripts/Node/LPDTL_discuss.txt
git rm vimfiles/vimoutliner/scripts/Node/Node.pm
git rm vimfiles/vimoutliner/scripts/Node/README.otl
git rm vimfiles/vimoutliner/scripts/Node/deletetest.otl
git rm vimfiles/vimoutliner/scripts/Node/example_attribs.pl
git rm vimfiles/vimoutliner/scripts/Node/example_bylevel.pl
git rm vimfiles/vimoutliner/scripts/Node/example_delete.pl
git rm vimfiles/vimoutliner/scripts/Node/example_hello.pl
git rm vimfiles/vimoutliner/scripts/Node/example_insert.pl
git rm vimfiles/vimoutliner/scripts/Node/example_nodepath.pl
git rm vimfiles/vimoutliner/scripts/Node/example_otl2markup.pl
git rm vimfiles/vimoutliner/scripts/Node/example_parse.pl
git rm vimfiles/vimoutliner/scripts/Node/myapp.cfg
git rm vimfiles/vimoutliner/scripts/fs2otl
git rm vimfiles/vimoutliner/scripts/otl2aft.awk
git rm vimfiles/vimoutliner/scripts/otl2aft.pdf
git rm vimfiles/vimoutliner/scripts/otl2docbook.pl
git rm vimfiles/vimoutliner/scripts/otl2html.py
git rm vimfiles/vimoutliner/scripts/otl2html_autonumbered.css
git rm vimfiles/vimoutliner/scripts/otl2html_nnnnnn.css
git rm vimfiles/vimoutliner/scripts/otl2latex/README
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.otl
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.pdf
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.png
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.py
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.tex
git rm vimfiles/vimoutliner/scripts/otl2latex/otl2latex.toc
git rm vimfiles/vimoutliner/scripts/otl2lyx.awk
git rm vimfiles/vimoutliner/scripts/otl2ooimpress.py
git rm vimfiles/vimoutliner/scripts/otl2ooimpress.sh
git rm vimfiles/vimoutliner/scripts/otl2table.py
git rm vimfiles/vimoutliner/scripts/otl2tags.py
git rm vimfiles/vimoutliner/scripts/otl2tags_freemind.conf
git rm vimfiles/vimoutliner/scripts/otl2tags_graphviz.conf
git rm vimfiles/vimoutliner/scripts/otl_handler/Apache/OTL.pm
git rm vimfiles/vimoutliner/scripts/otl_handler/README
git rm vimfiles/vimoutliner/scripts/otl_handler/devel-mode
git rm vimfiles/vimoutliner/scripts/otl_handler/javascript/jquery.js
git rm vimfiles/vimoutliner/scripts/otl_handler/javascript/theme2.js
git rm vimfiles/vimoutliner/scripts/otl_handler/javascript/theme3.js
git rm vimfiles/vimoutliner/scripts/otl_handler/sample.otl
git rm vimfiles/vimoutliner/scripts/otl_handler/styles/theme1.css
git rm vimfiles/vimoutliner/scripts/otl_handler/styles/theme2.css
git rm vimfiles/vimoutliner/scripts/otl_handler/styles/theme3.css
git rm vimfiles/vimoutliner/scripts/otlgrep.py
git rm vimfiles/vimoutliner/scripts/otlhead.sh
git rm vimfiles/vimoutliner/scripts/otlsplit.py
git rm vimfiles/vimoutliner/scripts/otltail.sh
git rm vimfiles/vimoutliner/scripts/outline_calendar/2005.otl
git rm vimfiles/vimoutliner/scripts/outline_calendar/vimrc
git rm vimfiles/vimoutliner/scripts/outline_calendar/vo_calendar_ctags.conf
git rm vimfiles/vimoutliner/scripts/outline_calendar/vo_calendar_generator.rb
git rm vimfiles/vimoutliner/scripts/outline_calendar/vo_calendar_readme.otl
git rm vimfiles/vimoutliner/scripts/outline_calendar/vo_calendar_shelf.otl
git rm vimfiles/vimoutliner/scripts/outline_calendar/vo_calendar_ui.sh
git rm vimfiles/vimoutliner/scripts/outline_freemind/freemind.py
git rm vimfiles/vimoutliner/scripts/outline_freemind/freemind_outline.py
git rm vimfiles/vimoutliner/scripts/outline_freemind/otl.py
git rm vimfiles/vimoutliner/scripts/outline_freemind/outline_freemind.py
git rm vimfiles/vimoutliner/scripts/outline_freemind/test.otl
git rm vimfiles/vimoutliner/scripts/outline_freemind/test.sh
git rm vimfiles/vimoutliner/scripts/vo2html.rb
git rm vimfiles/vimoutliner/scripts/vo2odp.rb
git rm vimfiles/vimoutliner/scripts/vo2xo.rb
git rm vimfiles/vimoutliner/scripts/votl_maketags.1
git rm vimfiles/vimoutliner/scripts/votl_maketags.pl
git rm vimfiles"/vimoutliner/scripts/votl_maketags.pl_15\357\200\27245\357\200\27245_2014-06-06.old"